# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Our first job, Checkstyle (using clang-tidy
  Checkstyle:
    # The type of runner that the job will run on, windows in our case.
    runs-on: linux-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: ZedThree/clang-tidy-review@v0.2.0
        id: review
      # If there are any comments, fail the check
      - if: steps.review.outpus.total_comments > 0
        run: exit 1
